spring.application.name=server-rivage
# Port pour Spring Boot Web (Tomcat) - Console H2
server.port=8082
# Port pour les endpoints SOAP (JAX-WS)
soap.port=8081
# Racine des endpoints SOAP pour ce module; Publisher publie /agency et /hotel sous cette racine
soap.path=/hotel-rivage
# Publier la variante debug sur un chemin distinct pour ?viter le conflit avec l?impl?mentation r?elle
soap.path.hotelServiceDebugImpl=/hotel-debug

# Configuration H2 Database pour Rivage
spring.datasource.url=jdbc:h2:file:./data/hotel-rivage-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=rivage
spring.datasource.password=rivage
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

