
package org.examples.client.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HotelService", targetNamespace = "http://service.hotel.examples.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HotelService {


    /**
     * 
     * @param arg0
     * @return
     *     returns org.examples.client.stub.ReservationConfirmationDTO
     * @throws ServiceFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "makeReservation", targetNamespace = "http://service.hotel.examples.org/", className = "org.examples.client.stub.MakeReservation")
    @ResponseWrapper(localName = "makeReservationResponse", targetNamespace = "http://service.hotel.examples.org/", className = "org.examples.client.stub.MakeReservationResponse")
    @Action(input = "http://service.hotel.examples.org/HotelService/makeReservationRequest", output = "http://service.hotel.examples.org/HotelService/makeReservationResponse", fault = {
        @FaultAction(className = ServiceFault_Exception.class, value = "http://service.hotel.examples.org/HotelService/makeReservation/Fault/ServiceFault")
    })
    public ReservationConfirmationDTO makeReservation(
        @WebParam(name = "arg0", targetNamespace = "")
        ReservationRequestDTO arg0)
        throws ServiceFault_Exception
    ;

    /**
     * 
     * @return
     *     returns org.examples.client.stub.CatalogDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCatalog", targetNamespace = "http://service.hotel.examples.org/", className = "org.examples.client.stub.GetCatalog")
    @ResponseWrapper(localName = "getCatalogResponse", targetNamespace = "http://service.hotel.examples.org/", className = "org.examples.client.stub.GetCatalogResponse")
    @Action(input = "http://service.hotel.examples.org/HotelService/getCatalogRequest", output = "http://service.hotel.examples.org/HotelService/getCatalogResponse")
    public CatalogDTO getCatalog();

    /**
     * 
     * @param arg0
     * @return
     *     returns org.examples.client.stub.SearchOffersResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchOffers", targetNamespace = "http://service.hotel.examples.org/", className = "org.examples.client.stub.SearchOffers")
    @ResponseWrapper(localName = "searchOffersResponse", targetNamespace = "http://service.hotel.examples.org/", className = "org.examples.client.stub.SearchOffersResponse")
    @Action(input = "http://service.hotel.examples.org/HotelService/searchOffersRequest", output = "http://service.hotel.examples.org/HotelService/searchOffersResponse")
    public SearchOffersResponseDTO searchOffers(
        @WebParam(name = "arg0", targetNamespace = "")
        SearchCriteriaDTO arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "http://service.hotel.examples.org/", className = "org.examples.client.stub.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://service.hotel.examples.org/", className = "org.examples.client.stub.PingResponse")
    @Action(input = "http://service.hotel.examples.org/HotelService/pingRequest", output = "http://service.hotel.examples.org/HotelService/pingResponse")
    public String ping();

}
