spring.application.name=server-opera
server.port=8082
# Racine des endpoints SOAP pour ce module; Publisher publie /agency et /hotel sous cette racine
soap.path=/hotel-opera
# Chemin spécifique pour le bean de debug afin d?éviter collision
soap.path.hotelServiceDebugImpl=/hotel-opera/hotel-debug
